version: '3.7'

services:
  database:
    image: postgres:13.2
    volumes:
      - ./volumes/postgres:/data/user-db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

  user-api:
    build: ./
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - ./:/app:cached
    environment:
      DATABASE_PORT: $DATABASE_PORT
    ports:
      - $API_PORT:$API_PORT
